// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8H3y8q-2qDvBvoT_yW4jsVdbnnXSYagQ',
    appId: '1:184555898544:android:b22bf1b1513460c13f5d75',
    messagingSenderId: '184555898544',
    projectId: 'exam-f10db',
    storageBucket: 'exam-f10db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_puMqxNzS6C3etkEAJsuUUdslWzQ8jSg',
    appId: '1:184555898544:ios:507889f2d5b793003f5d75',
    messagingSenderId: '184555898544',
    projectId: 'exam-f10db',
    storageBucket: 'exam-f10db.firebasestorage.app',
    iosBundleId: 'com.example.exam',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgwbJYwHQXQ_OdSLGiyDpCQx8x4oZFrAA',
    appId: '1:184555898544:web:c794613fea6c5a023f5d75',
    messagingSenderId: '184555898544',
    projectId: 'exam-f10db',
    authDomain: 'exam-f10db.firebaseapp.com',
    storageBucket: 'exam-f10db.firebasestorage.app',
    measurementId: 'G-M24Y2VRVES',
  );

}